"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
from python_grpc_boilerplate.protobuf import messenger_pb2

class MessengerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    SendMessage: grpc.UnaryUnaryMultiCallable[
        messenger_pb2.Request, messenger_pb2.Response
    ] = ...

class MessengerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SendMessage(
        self,
        request: messenger_pb2.Request,
        context: grpc.ServicerContext,
    ) -> messenger_pb2.Response: ...

def add_MessengerServicer_to_server(
    servicer: MessengerServicer, server: grpc.Server
) -> None: ...
