# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_grpc_template/protobuf/messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-python_grpc_template/protobuf/messenger.proto\x12\tmessenger\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\tMessenger\x12\x38\n\x0bSendMessage\x12\x12.messenger.Request\x1a\x13.messenger.Response\"\x00\x32J\n\x0e\x41syncMessenger\x12\x38\n\x0bSendMessage\x12\x12.messenger.Request\x1a\x13.messenger.Response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'python_grpc_template.protobuf.messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'python_grpc_template.protobuf.messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Response)
  })
_sym_db.RegisterMessage(Response)

_MESSENGER = DESCRIPTOR.services_by_name['Messenger']
_ASYNCMESSENGER = DESCRIPTOR.services_by_name['AsyncMessenger']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=60
  _REQUEST._serialized_end=83
  _RESPONSE._serialized_start=85
  _RESPONSE._serialized_end=112
  _MESSENGER._serialized_start=114
  _MESSENGER._serialized_end=183
  _ASYNCMESSENGER._serialized_start=185
  _ASYNCMESSENGER._serialized_end=259
# @@protoc_insertion_point(module_scope)
